# Generated by Django 3.1 on 2023-07-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_reviewrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
